export const categories = [
  { id: "DR", name: "Deportes y Recreación" },
  { id: "AC", name: "Arte y Cultura" },
  { id: "FF", name: "Festivales y Ferias" },
  { id: "EA", name: "Educación y Aprendizaje" },
  { id: "CT", name: "Ciencia y Tecnología" },
  { id: "TM", name: "Talleres y Manualidades" },
  { id: "NM", name: "Naturaleza y Medio Ambiente" },
  { id: "GA", name: "Gastronomía" },
  { id: "JE", name: "Juegos y Entretenimiento" },
  { id: "EF", name: "Eventos Familiares" },
  { id: "ES", name: "Eventos Sociales" },
  { id: "BS", name: "Bienestar y Salud" },
  { id: "FT", name: "Festividades y Tradiciones" },
  { id: "JD", name: "Juventud y Desarrollo Personal" },
];

export const cities = [
  { id: "ES-TF-001", name: "Adeje" },
  { id: "ES-TF-002", name: "Arafo" },
  { id: "ES-TF-003", name: "Arico" },
  { id: "ES-TF-004", name: "Arona" },
  { id: "ES-TF-005", name: "Buenavista del Norte" },
  { id: "ES-TF-006", name: "Candelaria" },
  { id: "ES-TF-007", name: "El Rosario" },
  { id: "ES-TF-008", name: "El Sauzal" },
  { id: "ES-TF-009", name: "Fasnia" },
  { id: "ES-TF-010", name: "Garachico" },
  { id: "ES-TF-011", name: "Granadilla de Abona" },
  { id: "ES-TF-012", name: "La Guancha" },
  { id: "ES-TF-013", name: "Guía de Isora" },
  { id: "ES-TF-014", name: "Güímar" },
  { id: "ES-TF-015", name: "Icod de los Vinos" },
  { id: "ES-TF-016", name: "La Matanza de Acentejo" },
  { id: "ES-TF-017", name: "La Orotava" },
  { id: "ES-TF-018", name: "La Victoria de Acentejo" },
  { id: "ES-TF-019", name: "Los Realejos" },
  { id: "ES-TF-020", name: "Los Silos" },
  { id: "ES-TF-021", name: "Puerto de la Cruz" },
  { id: "ES-TF-022", name: "San Cristóbal de La Laguna" },
  { id: "ES-TF-023", name: "San Juan de la Rambla" },
  { id: "ES-TF-024", name: "San Miguel de Abona" },
  { id: "ES-TF-025", name: "Santa Cruz de Tenerife" },
  { id: "ES-TF-026", name: "Santa Úrsula" },
  { id: "ES-TF-027", name: "Santiago del Teide" },
  { id: "ES-TF-028", name: "Tacoronte" },
  { id: "ES-TF-029", name: "Tegueste" },
  { id: "ES-TF-030", name: "Vilaflor" },
  { id: "ES-TF-031", name: "Valle de Guerra" },
];
